version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"