name: hr-system build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: high-load-systems/hr-system
    steps:
    - name: get source code
      uses: actions/checkout@v3

    - name: setup cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: build with maven
      run: mvn -B clean install